# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20160619_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_details',
            name='Comments',
            field=models.ForeignKey(default='one', on_delete=django.db.models.deletion.CASCADE, to='articles.Comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
