# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-01 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20160619_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_details',
            name='Comments',
        ),
    ]
