# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-02 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_details_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_details',
            name='Article',
            field=models.TextField(blank=True),
        ),
    ]
