# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-22 16:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_details_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_details',
            name='Id',
            field=models.IntegerField(default=id),
        ),
        migrations.AlterField(
            model_name='article_details',
            name='time',
            field=models.DateField(default=datetime.datetime(2016, 8, 22, 16, 25, 16, 285089)),
        ),
    ]
