# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20160824_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30)),
                ('comment', models.TextField()),
                ('time', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article_details')),
            ],
        ),
    ]
