# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_article_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_comment',
            old_name='products',
            new_name='article',
        ),
    ]
