# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(default='', max_length=30)),
                ('Discription', models.TextField()),
                ('Price', models.IntegerField()),
                ('pic1', models.ImageField(blank=True, upload_to=b'')),
                ('pic2', models.ImageField(blank=True, upload_to=b'')),
                ('pic3', models.ImageField(blank=True, upload_to=b'')),
                ('pic4', models.ImageField(blank=True, upload_to=b'')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
