# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160828_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categor',
        ),
    ]
