# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20160828_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Discription',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category'),
        ),
    ]
