# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20160828_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pic4',
        ),
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category'),
        ),
    ]
