# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20160902_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
