# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20160909_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='read',
            field=models.CharField(blank=True, default='no', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category'),
        ),
    ]
