# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('enter_password', models.CharField(max_length=30)),
            ],
        ),
    ]
