# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='use_r',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='use_r', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to='register.Sign_up'),
        ),
    ]
