# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20160828_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='use_r',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='use_r', to=settings.AUTH_USER_MODEL),
        ),
    ]
