# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_userprofile_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='Email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='Name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='enter_password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
