# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
