# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Phone_number',
            field=models.CharField(default='000 000 000', max_length=12),
        ),
    ]
