# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 09:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20160902_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name1', to=settings.AUTH_USER_MODEL),
        ),
    ]
