# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-09 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_auto_20160902_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign_up',
            old_name='Name',
            new_name='First_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
