# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-09 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_auto_20161009_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Date_of_birth',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Year_of_birth',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
