# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-12 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_auto_20161009_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='First_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='enter_password',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
