# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-25 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_auto_20161012_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Phone_number',
            field=models.CharField(blank=True, default='000 000 000', max_length=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Year_of_birth',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
