# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_auto_20161025_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active',
            field=models.CharField(choices=[('1', 'true'), ('2', 'false')], max_length=5, null=True),
        ),
    ]
