# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-11 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_userprofile_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='active',
            field=models.CharField(choices=[('1', 'true'), ('2', 'false')], default='yes', max_length=5, null=True),
        ),
    ]
