# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_auto_20161111_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picToShow',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Phone_number',
            field=models.CharField(blank=True, default='000 000 000', max_length=13),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Year_of_birth',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
