# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_auto_20161115_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picToShow',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
