# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_auto_20161009_1553'),
        ('UserPreference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='use_r',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.userprofile'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='I_like',
            field=models.CharField(max_length=70),
        ),
    ]
