# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPreference', '0003_auto_20161010_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='I_like',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
