# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
